loginUrl="/api/cust/login"
loginPwdUrl="/api/cust/pwd/login"
updatePwdUrl="/api/cust/pwd/update"
trackDetailUrl="/api/third/track/detail"
certAuthUrl='/api/cust/auth/cert'
authReviewUrl='/api/cust/auth/review'
addressUrl='/api/cust_india/cert/save_address?lang=en'
singleAuthUrl='/api/cust_india/query/single_cust_auth?lang=en'
workAuthUrl='/api/cust/auth/work'
grabDataUrl='/api/common/grab/app_grab_data'
contactAuthUrl='/api/cust/auth/other/contact'
withdrawUrl='/api/loan/apply'
bankAuthUrl='/api/cust/auth/bank'
confirmWithdrawUrl='/api/trade/fin/confirm/withdraw'
finwithdrawUrl='/api/trade/fin/withdraw'
checkBankUrl='/api/cust_india/bank/checkBankCard?lang=en'
fundAccountUrl='/api/trade/cust/create/contact/fund_account'
instalmentUrl="/api/loan_info/trial/instalment?lang=en"
lessWithdrawUrl="/api/trade/fin/less/withdraw?lang=en"
repayUrl="/api/trade/fin/repay"
payoutWebhookUrl="/api/trade/stp_payout/annon/event/webhook"
repaymentWebhookUrl="/api/trade/stp_repayment/annon/event/webhook"
conektaWebhookUrl="/api/trade/conekta/annon/event/webhook"
